/*
 * Project Euler in C
 * Copyright (c) Jeremiah Griffin 2016
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
 * Problem 002: Even Fibonacci numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

#include "solution.h"

#define LIMIT 4000000

static eu_result_t solve() {
    eu_result_t table[64] = {1, 2}; /* 1 & 2 are the first two in Fib_n */
    eu_result_t sum = 2; /* 2 is the only pre-calculated even Fib_n */
    for (size_t i = 2; i < sizeof table / sizeof *table; ++i) {
        table[i] = table[i - 1] + table[i - 2];
        if (table[i] > LIMIT) {
            break;
        }
        if ((table[i] & 1) == 0) {
            /* Bit 0 is not set in even numbers */
            sum += table[i];
        }
    }
    return sum;
}

const eu_solution_t eu_solution002 = {2, solve};
